// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TaskSystem.DL;

namespace TaskSystem.DL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180117204949_Invoice_RemoveTaskId")]
    partial class Invoice_RemoveTaskId
    {
    }
}
